CREATE SMALLFILE TABLESPACE KASHICAPITAL_DATA01 DATAFILE 'C:\Projects\KASHICAPITAL' SIZE 200M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER KASHICAPITAL_DBA IDENTIFIED BY KASHICAPITAL DEFAULT TABLESPACE KASHICAPITAL_DATA01 TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON KASHICAPITAL_DATA01;

GRANT dba to KASHICAPITAL_DBA;

 CREATE TABLE "LOAN" (
"ID" NUMBER(10,0) NOT NULL ENABLE,  
"STATUS" NUMBER(1,0), 
"DATE_CREATED" TIMESTAMP (6), 
"DATE_MODIFIED" TIMESTAMP (6), 
	 PRIMARY KEY ("ID") ENABLE );
-----------

CREATE TABLE "LOAN_APPLICATION_DETAIL" (
"ID" NUMBER(10,0) NOT NULL,
"LOAN_ID" NUMBER(10,0) NOT NULL,
"CODE" VARCHAR2(50 CHAR),
"PRESENT_CUSTOMER" NUMBER(1,0),
"NEW_CUSTOMER" NUMBER(1,0),
"EXISTING_CUSTOMER_DETAIL" VARCHAR2(255 CHAR),
"APPLICANT_NAME" VARCHAR2(50 CHAR),
"COAPPLICANT_NAME" VARCHAR2(50 CHAR),
"APPLICATION_SERIOL_NUMBER" VARCHAR2(50 CHAR),
"CUSTOMER_NUMBER" VARCHAR2(50 CHAR),
"LOAN_OFFICER_NAME" VARCHAR2(50 CHAR),
"BRANCH_CODE" VARCHAR2(50 CHAR),
"STATE" VARCHAR2(50 CHAR),
"LOAN_TYPE_CODE" VARCHAR2(50 CHAR),
"OCCUPATIONAL_INCOME" NUMBER(10,0),
"DOMESTIC_INCOME" NUMBER(10,0),
"INCOME_FROM_RENT" NUMBER(10,0),
"INCOME_FROM_OTHER_MEMBER" NUMBER(10,0),
"AGRICULTURAL_INCOME" NUMBER(10,0),
"SAL_INCOME" NUMBER(10,0),
"INCOME_FROM_MILK" NUMBER(10,0),
"INCOME_FROM_OTHER_SOURCE" NUMBER(10,0),
"TOTAL_HOUSEHOLD_INCOME" NUMBER(10,0),
"DATE_CREATED" TIMESTAMP (6), 
"DATE_MODIFIED" TIMESTAMP (6),
	 PRIMARY KEY ("ID") ENABLE,
   CONSTRAINT "LOAN_APP_DETAIL_FK01" FOREIGN KEY ("LOAN_ID") REFERENCES "LOAN" ("ID") ENABLE);
-----------

CREATE TABLE "LOAN_CUSTOMER_DEPENDENTS" (
"ID" NUMBER(10,0) NOT NULL,
"LOAN_ID" NUMBER(10,0) NOT NULL,
"NAME" VARCHAR2(50 CHAR),
"RELATION" VARCHAR2(100 CHAR),
"AGE" VARCHAR2(10 CHAR),
"BUSINESS" VARCHAR2(255 CHAR),
"INCOME" VARCHAR2(50 CHAR),
"MOBILE_NUMBER" VARCHAR2(20 CHAR),
"LIVING_STATUS" VARCHAR2(50 CHAR),
"DATE_CREATED" TIMESTAMP (6), 
"DATE_MODIFIED" TIMESTAMP (6),
   PRIMARY KEY ("ID") ENABLE,
   CONSTRAINT "LOAN_CUST_DEPENDENTS_FK01" FOREIGN KEY ("LOAN_ID") REFERENCES "LOAN" ("ID") ENABLE);
   ----------

CREATE TABLE "LOAN_TYPE" (
"LOAN_TYPE_ID" NUMBER(10,0) NOT NULL,
"LOAN_TYPE_CODE" VARCHAR2(50 CHAR),
"LOAN_TYPE_NAME" VARCHAR2(50 CHAR),
   PRIMARY KEY ("LOAN_TYPE_ID") ENABLE );
--------------

CREATE TABLE "APPLICANT_BUSINESS_DETAIL" (
"ID" NUMBER(10,0) NOT NULL,
"LOAN_ID" NUMBER(10,0) NOT NULL,
"ENTERPRISE_NAME" VARCHAR2(100 CHAR),
"BUSINESS_ADDRESS" VARCHAR2(255 CHAR),
"CITY" VARCHAR2(50 CHAR),
"POST_OFFICE" VARCHAR2(50 CHAR),
"DISTRICT" VARCHAR2(50 CHAR),
"STATE" VARCHAR2(50 CHAR),
"PIN_CODE" VARCHAR2(50 CHAR),
"PHONE_NUMBER" VARCHAR2(20 CHAR),
"MOBILE_NUMBER" VARCHAR2(20 CHAR),
"EMAIL" VARCHAR2(50 CHAR),
"PRESENT_BUSINESS_ACTIVITY" VARCHAR2(255 CHAR),
"PROPOSED_BUSINESS_ACTIVITY" VARCHAR2(255 CHAR),
"START_DATE" TIMESTAMP (6),
"TYPE_OF_COMPANY" VARCHAR2(50 CHAR),
"BUSINESS_PREMISES_TYPE" VARCHAR2(50 CHAR),
"GST_EXIST" NUMBER(1,0),
"GST_NUMBER" VARCHAR2(50 CHAR),
"REGISTERED_OFFICE" VARCHAR2(100 CHAR),
"NUMBER_OF_EMPLOYEE" VARCHAR2(20 CHAR),
"REGISTERED_UNIT" VARCHAR2(20 CHAR),
"DATE_CREATED" TIMESTAMP (6), 
"DATE_MODIFIED" TIMESTAMP (6),
   PRIMARY KEY ("ID") ENABLE,
   CONSTRAINT "APP_BUSINESS_DETAIL_FK01" FOREIGN KEY ("LOAN_ID") REFERENCES "LOAN" ("ID") ENABLE);
----------

CREATE TABLE "CUST_PARTNER_DETAIL" (
"ID" NUMBER(10,0) NOT NULL,
"LOAN_ID" NUMBER(10,0) NOT NULL,
"PARTNER_NAME" VARCHAR2(50 CHAR),
"PARTNER_GURDIAN_NAME" VARCHAR2(50 CHAR),
"DATE_OF_BIRTH" TIMESTAMP (6),
"GENDER" VARCHAR2(20 CHAR),
"QUALIFICATION" VARCHAR2(50 CHAR),
"YEARS_OF_EXPERIENCE" NUMBER(10,0),
"TYPE_OF_ACCOMODATION" VARCHAR2(20 CHAR),
"CAST" VARCHAR2(50 CHAR),
"RELIGION" VARCHAR2(50 CHAR),
"MOBILE_NUMBER" VARCHAR2(20 CHAR),
"PAN_NUMBER" VARCHAR2(20 CHAR),
"AADHAR_NUMBER" NUMBER(20,0),
"VOTER_CARD_NO" VARCHAR2(20 CHAR),
"DIN_NUMBER" VARCHAR2(20 CHAR),
"DATE_CREATED" TIMESTAMP (6), 
"DATE_MODIFIED" TIMESTAMP (6),
   PRIMARY KEY ("ID") ENABLE,
   CONSTRAINT "CUST_PARTNER_DETAIL_FK01" FOREIGN KEY ("LOAN_ID") REFERENCES "LOAN" ("ID") ENABLE);
-------------

CREATE TABLE "CUST_BANK_DETAIL" (
"ID" NUMBER(10,0) NOT NULL,
"LOAN_ID" NUMBER(10,0) NOT NULL,
"BANK_ACCOUNT_TYPE" VARCHAR2(50 CHAR),
"BANK_NAME" VARCHAR2(50 CHAR),
"BANK_BRANCH_NUMBER" VARCHAR2(50 CHAR),
"ACCOUNT_NUMBER" VARCHAR2(50 CHAR),
"ACCOUNT_START_DATE" TIMESTAMP (6),
"DEPOSIT_AMOUNT" NUMBER(10,0),
"DATE_CREATED" TIMESTAMP (6), 
"DATE_MODIFIED" TIMESTAMP (6),
   PRIMARY KEY ("ID") ENABLE,
   CONSTRAINT "CUST_BANK_DETAIL_FK01" FOREIGN KEY ("LOAN_ID") REFERENCES "LOAN" ("ID") ENABLE);
--------------
CREATE TABLE "CUST_LOAN_DETAIL" (
"ID" NUMBER(10,0) NOT NULL,
"LOAN_ID" NUMBER(10,0) NOT NULL,
"TYPE_OF_LOAN" VARCHAR2(20 CHAR),
"LOAN_COMPANY_NAME" VARCHAR2(50 CHAR),
"PURPOSE" VARCHAR2(255 CHAR),
"LOAN_AMOUNT" NUMBER(10,0),
"BALANCE_LOAN_AMOUNT" NUMBER(10,0),
"LOAN_TERM" VARCHAR2(255 CHAR),
"LOAN_INTEREST_RATE" NUMBER(10,0),
"LOAN_START_DATE" TIMESTAMP (6),
"LOAN_EMI_AMOUNT" NUMBER(10,0),
"LOAN_EMI_TYPE" VARCHAR2(50 CHAR),
"LOAN_SECURITY" VARCHAR2(50 CHAR),
"LOAN_AGREEMENT_INCORPORATED" VARCHAR2(50 CHAR),
"PRESENT_LOAN_STATUS" VARCHAR2(50 CHAR),
"DATE_CREATED" TIMESTAMP (6), 
"DATE_MODIFIED" TIMESTAMP (6),
   PRIMARY KEY ("ID") ENABLE,
   CONSTRAINT "CUST_LOAN_DETAIL_FK01" FOREIGN KEY ("LOAN_ID") REFERENCES "LOAN" ("ID") ENABLE);
--------
CREATE TABLE "LOAN_APPLICANT_COMMENTS" (
"ID" NUMBER(10,0) NOT NULL,
"LOAN_ID" NUMBER(10,0) NOT NULL,
"LOAN_STATUS" VARCHAR2(50 CHAR),
"COMMENTS" VARCHAR2(255 CHAR),
"COMMENT_BY_USER" NUMBER(10,0),
"DATE_OF_COMMENT" TIMESTAMP (6),
"DATE_CREATED" TIMESTAMP (6), 
"DATE_MODIFIED" TIMESTAMP (6),
	PRIMARY KEY("ID"),
	CONSTRAINT "LOAN_APPLICANT_COMMENTS_FK01" FOREIGN KEY("LOAN_ID") REFERENCES "LOAN"("ID") );

CREATE TABLE "LOAN_CUSTOMER_DOCUMENTS" (
"ID" NUMBER(10,0) NOT NULL,
"LOAN_ID" NUMBER(10,0) NOT NULL,
"DOCUMENT_NAME" VARCHAR2(50 CHAR),
"DOCUMENT_IMAGE" BLOB,
"DATE_CREATED" TIMESTAMP (6), 
"DATE_MODIFIED" TIMESTAMP (6),
	PRIMARY KEY("ID"),
	CONSTRAINT "LOAN_CUST_DOCS_FK01" FOREIGN KEY("LOAN_ID") REFERENCES "LOAN" ("ID") ENABLE );
-------------

Insert into LOAN (ID,STATUS,DATE_CREATED,DATE_MODIFIED) values (1110,1,to_timestamp('22-APR-19 11.57.15.432000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('22-APR-19 11.57.27.135000000 AM','DD-MON-RR HH.MI.SSXFF AM'));

Insert into LOAN_TYPE (LOAN_TYPE_ID,LOAN_TYPE_CODE,LOAN_TYPE_NAME) values (1,'L1','Loan Type 1');

Insert into APPLICANT_BUSINESS_DETAIL (ID,LOAN_ID,ENTERPRISE_NAME,BUSINESS_ADDRESS,CITY,POST_OFFICE,DISTRICT,STATE,PIN_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL,PRESENT_BUSINESS_ACTIVITY,PROPOSED_BUSINESS_ACTIVITY,START_DATE,TYPE_OF_COMPANY,BUSINESS_PREMISES_TYPE,GST_EXIST,GST_NUMBER,REGISTERED_OFFICE,NUMBER_OF_EMPLOYEE,REGISTERED_UNIT,DATE_CREATED,DATE_MODIFIED) values (1,1110,'Info Solution Pvt Ltd','PLOT 31313 PHASE 7, Mohali','MOHALI','PHASE 7','MOHALI','PUNJAB','160061','9888898888','9888898888','varun007@gmail.com','Growing','Growing',to_timestamp('01-APR-19 12.31.39.065000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Pvt Ltd','IT',1,'GSTN0000151','sample desc','100','80',to_timestamp('22-APR-19 12.26.29.976000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('22-APR-19 12.26.29.976000000 PM','DD-MON-RR HH.MI.SSXFF AM'));

Insert into CUST_BANK_DETAIL (ID,LOAN_ID,BANK_ACCOUNT_TYPE,BANK_NAME,BANK_BRANCH_NUMBER,ACCOUNT_NUMBER,ACCOUNT_START_DATE,DEPOSIT_AMOUNT,DATE_CREATED,DATE_MODIFIED) values (1,1110,'Saving','SBI','SBIN00013','105150215025',to_timestamp('01-APR-19 12.19.22.427000000 PM','DD-MON-RR HH.MI.SSXFF AM'),800000,to_timestamp('22-APR-19 12.19.38.972000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('22-APR-19 12.19.38.972000000 PM','DD-MON-RR HH.MI.SSXFF AM'));

Insert into CUST_LOAN_DETAIL (ID,LOAN_ID,TYPE_OF_LOAN,LOAN_COMPANY_NAME,PURPOSE,LOAN_AMOUNT,BALANCE_LOAN_AMOUNT,LOAN_TERM,LOAN_INTEREST_RATE,LOAN_START_DATE,LOAN_EMI_AMOUNT,LOAN_EMI_TYPE,LOAN_SECURITY,LOAN_AGREEMENT_INCORPORATED,PRESENT_LOAN_STATUS,DATE_CREATED,DATE_MODIFIED) values (1,1110,'1','SBI','Home Loan',1000000,1000000,'Desc Req',9,to_timestamp('22-APR-19 12.36.12.777000000 PM','DD-MON-RR HH.MI.SSXFF AM'),10100,'EMI_TYPE1','Company Docs','Desc Req','On going',to_timestamp('22-APR-19 12.38.00.319000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('22-APR-19 12.38.00.319000000 PM','DD-MON-RR HH.MI.SSXFF AM'));

Insert into CUST_PARTNER_DETAIL (ID,LOAN_ID,PARTNER_NAME,PARTNER_GURDIAN_NAME,DATE_OF_BIRTH,GENDER,QUALIFICATION,YEARS_OF_EXPERIENCE,TYPE_OF_ACCOMODATION,CAST,RELIGION,MOBILE_NUMBER,PAN_NUMBER,AADHAR_NUMBER,VOTER_CARD_NO,DIN_NUMBER,DATE_CREATED,DATE_MODIFIED) values (1,1110,'Nitin','Jeet Ram',to_timestamp('15-APR-75 12.39.21.748000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'M','MBA',15,'Accommodation1','Sharma','Hindu','9888898888','HDB75675S',1313315946,'VT5454','DIN4569',to_timestamp('22-APR-19 12.42.41.323000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('22-APR-19 12.42.41.323000000 PM','DD-MON-RR HH.MI.SSXFF AM'));

Insert into LOAN_APPLICANT_COMMENTS (ID,LOAN_ID,LOAN_STATUS,COMMENTS,COMMENT_BY_USER,DATE_OF_COMMENT,DATE_CREATED,DATE_MODIFIED) values (1,1110,'In Progress','Verification Pending',101,to_timestamp('22-APR-19 12.08.14.768000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('22-APR-19 12.08.14.768000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('22-APR-19 12.08.14.768000000 PM','DD-MON-RR HH.MI.SSXFF AM'));

Insert into LOAN_APPLICATION_DETAIL (ID,LOAN_ID,CODE,PRESENT_CUSTOMER,NEW_CUSTOMER,EXISTING_CUSTOMER_DETAIL,APPLICANT_NAME,COAPPLICANT_NAME,APPLICATION_SERIOL_NUMBER,CUSTOMER_NUMBER,LOAN_OFFICER_NAME,BRANCH_CODE,STATE,LOAN_TYPE_CODE,OCCUPATIONAL_INCOME,DOMESTIC_INCOME,INCOME_FROM_RENT,INCOME_FROM_OTHER_MEMBER,AGRICULTURAL_INCOME,SAL_INCOME,INCOME_FROM_MILK,INCOME_FROM_OTHER_SOURCE,TOTAL_HOUSEHOLD_INCOME,DATE_CREATED,DATE_MODIFIED) values (1110,1110,'L1110',0,1,'N/A','Varun','Ram','APP1110','1','Preet','LB00010','PUNJAB','1',10000,30000,60000,0,20000,30000,10000,20000,180000,to_timestamp('22-APR-19 12.08.14.768000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('22-APR-19 12.08.14.768000000 PM','DD-MON-RR HH.MI.SSXFF AM'));

Insert into LOAN_CUSTOMER_DEPENDENTS (ID,LOAN_ID,NAME,RELATION,AGE,BUSINESS,INCOME,MOBILE_NUMBER,LIVING_STATUS,DATE_CREATED,DATE_MODIFIED) values (1,1110,'Amit','Brother','45','Job','500000','9888898888','Active',to_timestamp('22-APR-19 12.08.14.768000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('22-APR-19 12.08.14.768000000 PM','DD-MON-RR HH.MI.SSXFF AM'));

Insert into LOAN_CUSTOMER_DOCUMENTS (ID,LOAN_ID,DOCUMENT_NAME,DATE_CREATED,DATE_MODIFIED) values (1,1110,'PAN',to_timestamp('22-APR-19 12.08.14.768000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('22-APR-19 12.08.14.768000000 PM','DD-MON-RR HH.MI.SSXFF AM'));

COMMIT;