CREATE TABLE LOAN (
ID numeric(10) NOT NULL ,  
CODE nvarchar(50),
STATUS nvarchar(50),
DATE_CREATED TIMESTAMP (6), 
DATE_MODIFIED TIMESTAMP (6), 
	 PRIMARY KEY (ID));
-----------

CREATE TABLE LOAN_APPLICATION_DETAIL (
ID numeric(10) NOT NULL,
LOAN_ID numeric(10) NOT NULL,
CODE nvarchar(50),
PRESENT_CUSTOMER numeric(1),
NEW_CUSTOMER numeric(1),
EXISTING_CUSTOMER_DETAIL nvarchar(255),
APPLICANT_NAME nvarchar(50),
COAPPLICANT_NAME nvarchar(50),
APPLICATION_SERIOL_NUMBER nvarchar(50),
CUSTOMER_NUMBER nvarchar(50),
LOAN_OFFICER_NAME nvarchar(50),
BRANCH_CODE nvarchar(50),
STATE nvarchar(50),
LOAN_TYPE_CODE nvarchar(50),
OCCUPATIONAL_INCOME numeric(10),
DOMESTIC_INCOME numeric(10),
INCOME_FROM_RENT numeric(10),
INCOME_FROM_OTHER_MEMBER numeric(10),
AGRICULTURAL_INCOME numeric(10),
SAL_INCOME numeric(10),
INCOME_FROM_MILK numeric(10),
INCOME_FROM_OTHER_SOURCE numeric(10),
TOTAL_HOUSEHOLD_INCOME numeric(10),
DATE_CREATED TIMESTAMP (6), 
DATE_MODIFIED TIMESTAMP (6),
	 PRIMARY KEY (ID) ,
   CONSTRAINT LOAN_APP_DETAIL_FK01 FOREIGN KEY (LOAN_ID) REFERENCES LOAN (ID));
-----------

CREATE TABLE LOAN_CUSTOMER_DEPENDENTS (
ID numeric(10) NOT NULL,
LOAN_ID numeric(10) NOT NULL,
NAME nvarchar(50),
RELATION nvarchar(100),
AGE nvarchar(10),
BUSINESS nvarchar(255),
INCOME nvarchar(50),
MOBILE_NUMBER nvarchar(20),
LIVING_STATUS nvarchar(50),
DATE_CREATED TIMESTAMP (6), 
DATE_MODIFIED TIMESTAMP (6),
   PRIMARY KEY (ID) ,
   CONSTRAINT LOAN_CUST_DEPENDENTS_FK01 FOREIGN KEY (LOAN_ID) REFERENCES LOAN (ID));
   ----------

CREATE TABLE LOAN_TYPE (
LOAN_TYPE_ID numeric(10) NOT NULL,
LOAN_TYPE_CODE nvarchar(50),
LOAN_TYPE_NAME nvarchar(50),
   PRIMARY KEY (LOAN_TYPE_ID));
--------------

CREATE TABLE APPLICANT_BUSINESS_DETAIL (
ID numeric(10) NOT NULL,
LOAN_ID numeric(10) NOT NULL,
ENTERPRISE_NAME nvarchar(100),
BUSINESS_ADDRESS nvarchar(255),
CITY nvarchar(50),
POST_OFFICE nvarchar(50),
DISTRICT nvarchar(50),
STATE nvarchar(50),
PIN_CODE nvarchar(50),
PHONE_NUMBER nvarchar(20),
MOBILE_NUMBER nvarchar(20),
EMAIL nvarchar(50),
PRESENT_BUSINESS_ACTIVITY nvarchar(255),
PROPOSED_BUSINESS_ACTIVITY nvarchar(255),
START_DATE TIMESTAMP (6),
TYPE_OF_COMPANY nvarchar(50),
BUSINESS_PREMISES_TYPE nvarchar(50),
GST_EXIST numeric(1),
GST_NUMBER nvarchar(50),
REGISTERED_OFFICE nvarchar(100),
NUMBER_OF_EMPLOYEE nvarchar(20),
REGISTERED_UNIT nvarchar(20),
DATE_CREATED TIMESTAMP (6), 
DATE_MODIFIED TIMESTAMP (6),
   PRIMARY KEY (ID) ,
   CONSTRAINT APP_BUSINESS_DETAIL_FK01 FOREIGN KEY (LOAN_ID) REFERENCES LOAN (ID));
----------

CREATE TABLE CUST_PARTNER_DETAIL (
ID numeric(10) NOT NULL,
LOAN_ID numeric(10) NOT NULL,
PARTNER_NAME nvarchar(50),
PARTNER_GURDIAN_NAME nvarchar(50),
DATE_OF_BIRTH TIMESTAMP (6),
GENDER nvarchar(20),
QUALIFICATION nvarchar(50),
YEARS_OF_EXPERIENCE numeric(10),
TYPE_OF_ACCOMODATION nvarchar(20),
CAST nvarchar(50),
RELIGION nvarchar(50),
MOBILE_NUMBER nvarchar(20),
PAN_NUMBER nvarchar(20),
AADHAR_NUMBER numeric(20),
VOTER_CARD_NO nvarchar(20),
DIN_NUMBER nvarchar(20),
DATE_CREATED TIMESTAMP (6), 
DATE_MODIFIED TIMESTAMP (6),
   PRIMARY KEY (ID) ,
   CONSTRAINT CUST_PARTNER_DETAIL_FK01 FOREIGN KEY (LOAN_ID) REFERENCES LOAN (ID));
-------------

CREATE TABLE CUST_BANK_DETAIL (
ID numeric(10) NOT NULL,
LOAN_ID numeric(10) NOT NULL,
BANK_ACCOUNT_TYPE nvarchar(50),
BANK_NAME nvarchar(50),
BANK_BRANCH_NUMBER nvarchar(50),
ACCOUNT_NUMBER nvarchar(50),
ACCOUNT_START_DATE TIMESTAMP (6),
DEPOSIT_AMOUNT numeric(10),
DATE_CREATED TIMESTAMP (6), 
DATE_MODIFIED TIMESTAMP (6),
   PRIMARY KEY (ID) ,
   CONSTRAINT CUST_BANK_DETAIL_FK01 FOREIGN KEY (LOAN_ID) REFERENCES LOAN (ID));
--------------
CREATE TABLE CUST_LOAN_DETAIL (
ID numeric(10) NOT NULL,
LOAN_ID numeric(10) NOT NULL,
TYPE_OF_LOAN nvarchar(20),
LOAN_COMPANY_NAME nvarchar(50),
PURPOSE nvarchar(255),
LOAN_AMOUNT numeric(10),
BALANCE_LOAN_AMOUNT numeric(10),
LOAN_TERM nvarchar(255),
LOAN_INTEREST_RATE numeric(10),
LOAN_START_DATE TIMESTAMP (6),
LOAN_EMI_AMOUNT numeric(10),
LOAN_EMI_TYPE nvarchar(50),
LOAN_SECURITY nvarchar(50),
LOAN_AGREEMENT_INCORPORATED nvarchar(50),
PRESENT_LOAN_STATUS nvarchar(50),
DATE_CREATED TIMESTAMP (6), 
DATE_MODIFIED TIMESTAMP (6),
   PRIMARY KEY (ID) ,
   CONSTRAINT CUST_LOAN_DETAIL_FK01 FOREIGN KEY (LOAN_ID) REFERENCES LOAN (ID));
--------
CREATE TABLE LOAN_APPLICANT_COMMENTS (
ID numeric(10) NOT NULL,
LOAN_ID numeric(10) NOT NULL,
LOAN_STATUS nvarchar(50),
COMMENTS nvarchar(255),
COMMENT_BY_USER numeric(10),
DATE_OF_COMMENT TIMESTAMP (6),
DATE_CREATED TIMESTAMP (6), 
DATE_MODIFIED TIMESTAMP (6),
	PRIMARY KEY(ID),
	CONSTRAINT LOAN_APPLICANT_COMMENTS_FK01 FOREIGN KEY(LOAN_ID) REFERENCES LOAN(ID) );

CREATE TABLE LOAN_CUSTOMER_DOCUMENTS (
ID numeric(10) NOT NULL,
LOAN_ID numeric(10) NOT NULL,
DOCUMENT_NAME nvarchar(50),
DOCUMENT_IMAGE BLOB,
DATE_CREATED TIMESTAMP (6), 
DATE_MODIFIED TIMESTAMP (6),
	PRIMARY KEY(ID),
	CONSTRAINT LOAN_CUST_DOCS_FK01 FOREIGN KEY(LOAN_ID) REFERENCES LOAN (ID));
-

Insert into LOAN (ID,STATUS,DATE_CREATED,DATE_MODIFIED) values (1110,'InProcess',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

Insert into LOAN_TYPE (LOAN_TYPE_ID,LOAN_TYPE_CODE,LOAN_TYPE_NAME) values (1,'L1','Personal Loan');

Insert into APPLICANT_BUSINESS_DETAIL (ID,LOAN_ID,ENTERPRISE_NAME,BUSINESS_ADDRESS,CITY,POST_OFFICE,DISTRICT,STATE,PIN_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL,PRESENT_BUSINESS_ACTIVITY,PROPOSED_BUSINESS_ACTIVITY,START_DATE,TYPE_OF_COMPANY,BUSINESS_PREMISES_TYPE,GST_EXIST,GST_NUMBER,REGISTERED_OFFICE,NUMBER_OF_EMPLOYEE,REGISTERED_UNIT,DATE_CREATED,DATE_MODIFIED) values (1,1110,'Info Solution Pvt Ltd','PLOT 31313 PHASE 7, Mohali','MOHALI','PHASE 7','MOHALI','PUNJAB','160061','9888898888','9888898888','varun007@gmail.com','Growing','Growing',CURRENT_TIMESTAMP,'Pvt Ltd','IT',1,'GSTN0000151','sample desc','100','80',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);